### ISSUE TITLE
No Converter found for ByteString to String

### ISSUE THREAD

**Issue by danielalejandrin** [GoogleCloudPlatform/spring-cloud-gcp#1276]
**Describe the bug**
When I'm using spring cloud openfeing with a custom configuration that has injected properties values with @Value annotation that are obtained from google secret manager I'm getting the following error
 `nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [com.google.protobuf.ByteString$LiteralByteString] to type [java.lang.String]"}`

I made a [example project](https://github.com/danielalejandrin/feign-secret-manager-no-converter) with the use of this type of configuration but it does not work cause I do not have a gcp subscription, but you can get the idea.

application.properties
AUTH_CREDENTIALS=${sm://secret}

As a summary I have the configuration file for feign similar to the following one

```
@Value("${AUTH_CREDENTIALS}") //These credentials are store in this way username:password so I need to encode and add to header

  private String authCredentials;

  @Bean
  public RequestInterceptor basicAuthRequestInterceptor(){
    return new CustomBasicAuthRequestInterceptor(authCredentials);
  }
```

An a feign client that uses the configuration

```
@FeignClient(value = "restClient", url = "${REST_URL}", configuration = CustomBasicAuthConfiguration.class)
public interface RestClient {

    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
    String request();
}
```

The request interceptor

```
    private String headerValue;

    public CustomBasicAuthRequestInterceptor(String authCredentials) {
        this(authCredentials, StandardCharsets.UTF_8);
    }

    public CustomBasicAuthRequestInterceptor(String authCredentials, Charset charset) {
        this.headerValue = "Basic " + new String(Base64.getEncoder().encode(authCredentials.getBytes(charset)));
    }

    @Override
    public void apply(RequestTemplate requestTemplate) {
        requestTemplate.header("Authorization", headerValue);
    }
```

When I'm using this way I get the exception described above, but when I annotated with @Component I don't get the exception.
I prefer the first way because I have several feign clients and this one needs this configuration.

Also in the example project you will find a workaround that was answered [here](https://stackoverflow.com/questions/70126474/no-converter-found-capable-of-converting-from-type-com-google-protobuf-bytestri)

**Comment by JoeWang1127** [comment]
Hi @danielalejandrin, there's an [example project](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample) showing how to export secret values from GCP Secret Manager. Please see what properties are needed in `application.properties` and `bootstrap.properties` (see [here](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#secret-manager) for more info). Basically, you don't need define any beans as the auto-configuration does all the things for you.

**Comment by danielalejandrin** [comment]
> Hi @danielalejandrin, there's an [example project](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample) showing how to export secret values from GCP Secret Manager. Please see what properties are needed in `application.properties` and `bootstrap.properties` (see [here](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#secret-manager) for more info). Basically, you don't need define any beans as the auto-configuration does all the things for you.

Hi @JoeWang1127  thank you for your answer. I´m following the example in the official documentation o [spring cloud openfeing](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/) so I'm using the way of creating beans to override the default configuration of a feign client, if I annotate this custom configuration with @Configuration or @Component it will be applied to all feign clients so I use the attribute of configuration. 
The secret is read when using the @Value annotation but it cannot be transform from ByteString to String, it's like the converter is not register in the auto-configuration of secrete manager when  using the attribute configuration of the feign client.

My understanding of the exmaple project is to use @ConfigurationProperties to inject the values in my configuration?

**Comment by damienburke** [comment]
i am getting this exact error too

**Comment by JoeWang1127** [comment]
Hi @danielalejandrin and @damienburke, the latest version of [this project](https://github.com/GoogleCloudPlatform/spring-cloud-gcp) solves this problem and you don't need to define a converter, but it's not released yet. My suggestion is you can keep the workaround for now and change it when we official release the next version.

**Comment by JoeWang1127** [comment]
Hi @damienburke and @danielalejandrin, we've released a new version of Spring Cloud GCP, could you please verify you project against the newest version?

**Comment by JoeWang1127** [comment]
Close this issue as no response, please reopen the issue if needed.

**Comment by bjeon-bakkt** [comment]
@JoeWang1127 what is the newest version that fixed? I am still facing the same issue with 3.4.0 and 3.5.0-SNAPSHOT.

**Comment by JoeWang1127** [comment]
Hi @bjeon-bakkt, you can try 3.4.0. Could you post a sample project which reproduce the issue in a Github repo?

**Comment by sleicht** [comment]
@JoeWang1127 I upgraded and enhanced the [example](https://github.com/sleicht/feign-secret-manager-no-converter) from @danielalejandrin. The described problem is still reproducible when running the test. The `FeignSecretmanagerNoConverterApplication` has a `@PostContruct` which adds the converter as workaround. If you remove this method, the test doesn't run anymore - the `ConverterNotFoundException` is thrown.
